version: '3.8'
services:
  govee2mqtt:
    image: ghcr.io/canduru4/govee:latest
    container_name: govee2mqtt
    restart: unless-stopped
    env_file:
      - .env
    # Host networking is required
    network_mode: host
